name: e-galax-touch-driver
version: '0.0.1'
summary: eGalax USB Touchscreen Driver
description: |
  This snap packages the eGalax touchscreen driver for Ubuntu Core. It ensures 
  proper touchscreen functionality by installing and running the eGTouch daemon.
base: core22
grade: stable
confinement: strict

apps:
  e-galax-touch-driver:
    command: bin/eGTouchD
    daemon: simple
    restart-condition: always
    plugs:
      - raw-usb
      - hardware-observe
      - input

parts:
  e-galax-touch-driver:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp setup.sh $SNAPCRAFT_PART_INSTALL/
      chmod +x $SNAPCRAFT_PART_INSTALL/setup.sh
      $SNAPCRAFT_PART_INSTALL/setup.sh --auto-install --prefix=$SNAPCRAFT_PART_INSTALL/bin
    stage-packages:
      - libudev1
      - libx11-6